name: Zarf Application Package Publishing

permissions:
  contents: read

on:
  workflow_dispatch:
    inputs:
      branchName:
        description: "Branch to build the packages from"
        required: true
        default: "main"

jobs:
  publish-packages:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: "Checkout Repo"
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          ref: ${{ github.event.inputs.branchName }}

      - name: Install The Latest Release Version of Zarf
        uses: defenseunicorns/setup-zarf@f95763914e20e493bb5d45d63e30e17138f981d6 # v1.0.0

      - name: "Login to GHCR"
        uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446 # v3.2.0
        with:
          registry: ghcr.io
          username: dummy
          password: ${{ github.token }}

      - name: Build And Publish Application Packages
        # Create the dos-games package with the cosign signature, publish to ghcr and copy the tags to allow 'uname -m' to work
        run: |
          zarf package create -o build -a amd64 examples/dos-games --signing-key=awskms:///${{ secrets.COSIGN_AWS_KMS_KEY }} --confirm
          zarf package create -o build -a arm64 examples/dos-games --signing-key=awskms:///${{ secrets.COSIGN_AWS_KMS_KEY }} --confirm

          # Publish a the signed dos-games package
          zarf package publish ./build/zarf-package-dos-games-amd64-1.0.0.tar.zst oci://ghcr.io/defenseunicorns/packages --key=https://zarf.dev/cosign.pub
          zarf package publish ./build/zarf-package-dos-games-arm64-1.0.0.tar.zst oci://ghcr.io/defenseunicorns/packages --key=https://zarf.dev/cosign.pub

          # Publish a skeleton of the dos-games package
          zarf package publish examples/dos-games oci://ghcr.io/defenseunicorns/packages
        env:
          AWS_REGION: ${{ secrets.COSIGN_AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.COSIGN_AWS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.COSIGN_AWS_ACCESS_KEY }}
